name: oqy
description: This is a IITU students diploma project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.3.2

dependencies:
  rich_editor: ^0.0.8 
  font_awesome_flutter:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.1
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  auto_route: ^7.9.2
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  flutter_quill: ^9.3.6
  flutter_slidable: ^3.0.1
  permission_handler: ^10.0.0
  chewie: ^1.2.2
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  equatable: ^2.0.5
  uuid: ^4.4.0
  awesome_select: ^6.0.0
  image_picker: ^0.8.4+4
  web_socket_channel: ^2.0.0
  video_player: ^2.2.12
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  pedantic_mono: any
  build_runner: null
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: GothicA1
      fonts:
        - asset: assets/fonts/GothicA1-Medium.ttf
          weight: 500
        - asset: assets/fonts/GothicA1-Bold.ttf
          weight: 700
        - asset: assets/fonts/GothicA1-Regular.ttf
          weight: 400

flutter_intl: 
  enabled: true
